/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


import {
  MultiSelect as MultiSelect
} from './components/multi-select/multi-select';

declare global {
  interface HTMLMultiSelectElement extends MultiSelect, HTMLElement {
  }
  var HTMLMultiSelectElement: {
    prototype: HTMLMultiSelectElement;
    new (): HTMLMultiSelectElement;
  };
  interface HTMLElementTagNameMap {
    "multi-select": HTMLMultiSelectElement;
  }
  interface ElementTagNameMap {
    "multi-select": HTMLMultiSelectElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "multi-select": JSXElements.MultiSelectAttributes;
    }
  }
  namespace JSXElements {
    export interface MultiSelectAttributes extends HTMLAttributes {
      labelAvailable?: string;
      labelSelected?: string;
      vertical?: boolean;
    }
  }
}

